In [2]:
import pandas as pd
import torch
import numpy as np
import random
from rbm import RBM


reviews = pd.read_csv('reviews.csv')
recipes = pd.read_csv('recipes.csv')



In [ ]:
reviews.head()

user_id  recipe_id        date  rating  \
0    38094      40893  2003-02-17       4   
1  1293707      40893  2011-12-21       5   
2     8937      44394  2002-12-01       4   
3   126440      85009  2010-02-27       5   
4    57222      85009  2011-10-01       5   

                                              review  
0  Great with a salad. Cooked on top of stove for...  
1  So simple, so delicious! Great for chilly fall...  
2  This worked very well and is EASY.  I used not...  
3  I made the Mexican topping and took it to bunk...  
4  Made the cheddar bacon topping, adding a sprin...

In [ ]:
recipes.index

RangeIndex(start=0, stop=231637, step=1)

In [ ]:
# reviews.merge(recipes, how='inner', left_on='recipe_id', right_on='id')

In [ ]:
df = reviews[['user_id', 'recipe_id']]

In [ ]:
df

user_id  recipe_id
0             38094      40893
1           1293707      40893
2              8937      44394
3            126440      85009
4             57222      85009
...             ...        ...
1132362      116593      72730
1132363      583662     386618
1132364      157126      78003
1132365       53932      78003
1132366  2001868099      78003

[1132367 rows x 2 columns]

In [ ]:

num_vis =  len(df)
rbm = RBM(0.01, 188, num_vis)

reviews = reviews.iloc[:5000,:]

unique_att = reviews['recipe_id'].unique()

unique_att.sort()
att_index = [i for i in range(len(unique_att))]
rbm_att_df = pd.DataFrame(list(zip(att_index,unique_att)), columns =['rbm_att_id','recipe_id'])
print(reviews)
joined = reviews.merge(rbm_att_df, on='recipe_id')
# print(joined)

In [ ]:
joined = joined[['user_id','recipe_id','rbm_att_id','rating']]
readers_group = joined.groupby('user_id')

total = []
for readerID, curReader in readers_group:
    temp = np.zeros(len(reviews))
    for num, book in curReader.iterrows():
        temp[book['rbm_att_id']] = book['rating']
    total.append(temp)


NameError: name 'joined' is not defined

In [ ]:
total

[array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([5., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 

In [ ]:
len(total)

3447

In [ ]:
len(total[0])

5000

In [ ]:
total_data = total
random.shuffle(total_data)
n = len(total_data)
print("Total size of the data is: {0}".format(n))
size_train = int(n * 0.75)
X_train = total_data[:size_train]
X_valid = total_data[size_train:]
train, valid = X_train, X_valid
print("Size of the training data is: {0}".format(len(X_train)))
print("Size of the validation data is: {0}".format(len(X_valid)))


Total size of the data is: 3447
Size of the training data is: 2585
Size of the validation data is: 862


In [ ]:
rbm.training(train, valid, 1, '100', 8, True, True, 'filename')

AttributeError: 'RBM' object has no attribute 'training'